// Commandgen generates the registry for the per-command descriptors.
//
// Go compiles packages statically, so the runtime cannot dynamic-import newly
// added source files. This small build-time generator provides the same
// folder-oriented authoring workflow as the old TypeScript gateway while
// keeping the resulting binary deterministic and portable.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const commandPackageImport = "github.com/Chomosuke9/WazzapAgent-Go/internal/command"

func main() {
	dir := flag.String("dir", ".", "directory containing command descriptors")
	out := flag.String("out", "registry_gen.go", "generated output file name")
	flag.Parse()
	if err := generate(*dir, *out); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func generate(dirName, outName string) error {
	entries, err := os.ReadDir(dirName)
	if err != nil {
		return fmt.Errorf("read command directory: %w", err)
	}
	fileSet := token.NewFileSet()
	packageName := ""
	descriptorNames := make([]string, 0, len(entries))
	seen := make(map[string]struct{})
	for _, entry := range entries {
		name := entry.Name()
		if entry.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") || name == outName {
			continue
		}
		path := filepath.Join(dirName, name)
		file, err := parser.ParseFile(fileSet, path, nil, 0)
		if err != nil {
			return fmt.Errorf("parse %s: %w", path, err)
		}
		if packageName == "" {
			packageName = file.Name.Name
		} else if packageName != file.Name.Name {
			return fmt.Errorf("command directory contains multiple packages: %s and %s", packageName, file.Name.Name)
		}
		for _, declaration := range file.Decls {
			general, ok := declaration.(*ast.GenDecl)
			if !ok || general.Tok != token.VAR {
				continue
			}
			for _, specification := range general.Specs {
				value, ok := specification.(*ast.ValueSpec)
				// Registration is intentionally independent from Permission. A
				// descriptor with !fromMe is still injected; the expression is
				// evaluated only when an invocation reaches Registry.Dispatch.
				if !ok || !isDescriptorSpec(value) {
					continue
				}
				for _, identifier := range value.Names {
					if !identifier.IsExported() {
						return fmt.Errorf("command descriptor %s must be exported", identifier.Name)
					}
					if _, exists := seen[identifier.Name]; exists {
						return fmt.Errorf("duplicate command descriptor variable %s", identifier.Name)
					}
					seen[identifier.Name] = struct{}{}
					descriptorNames = append(descriptorNames, identifier.Name)
				}
			}
		}
	}
	if packageName == "" {
		return fmt.Errorf("no Go command files found in %s", dirName)
	}
	if len(descriptorNames) == 0 {
		return fmt.Errorf("no command.Descriptor variables found in %s", dirName)
	}
	sort.Strings(descriptorNames)

	var source bytes.Buffer
	fmt.Fprintln(&source, "// Code generated by commandgen; DO NOT EDIT.")
	fmt.Fprintln(&source)
	fmt.Fprintf(&source, "package %s\n\n", packageName)
	fmt.Fprintf(&source, "import %q\n\n", commandPackageImport)
	fmt.Fprintln(&source, "var Descriptors = []command.Descriptor{")
	for _, name := range descriptorNames {
		fmt.Fprintf(&source, "\t%s,\n", name)
	}
	fmt.Fprintln(&source, "}")

	formatted, err := format.Source(source.Bytes())
	if err != nil {
		return fmt.Errorf("format generated registry: %w", err)
	}
	outputPath := filepath.Join(dirName, outName)
	if previous, readErr := os.ReadFile(outputPath); readErr == nil && bytes.Equal(previous, formatted) {
		return nil
	}
	if err := os.WriteFile(outputPath, formatted, 0o600); err != nil {
		return fmt.Errorf("write generated registry: %w", err)
	}
	return nil
}

func isDescriptorType(expression ast.Expr) bool {
	selector, ok := expression.(*ast.SelectorExpr)
	if !ok || selector.Sel.Name != "Descriptor" {
		return false
	}
	_, ok = selector.X.(*ast.Ident)
	return ok
}

func isDescriptorSpec(value *ast.ValueSpec) bool {
	if isDescriptorType(value.Type) {
		return true
	}
	for _, expression := range value.Values {
		literal, ok := expression.(*ast.CompositeLit)
		if ok && isDescriptorType(literal.Type) {
			return true
		}
	}
	return false
}
