//go:build gui

package frontend

import "embed"

// Assets contains the production frontend bundle generated by the frontend build.
// The bundle must exist before compiling the GUI target; no placeholder is embedded.
//
//go:embed all:dist
var Assets embed.FS
