version: '3'

includes:
  common: ./build/Taskfile.yml
  windows: ./build/windows/Taskfile.yml
  linux: ./build/linux/Taskfile.yml
  darwin: ./build/darwin/Taskfile.yml
  android: ./build/android/Taskfile.yml

vars:
  APP_NAME: WazzapAgent
  BIN_DIR: bin
  NPM: '{{.NPM | default "npm"}}'
  VITE_PORT: '{{.WAILS_VITE_PORT | default 9245}}'

tasks:
  build:
    summary: Build the GUI for the current desktop host
    cmds:
      - task: '{{OS}}:build'

  package:
    summary: Build the production GUI for the current desktop host
    cmds:
      - task: '{{OS}}:package'

  run:
    summary: Run the already built GUI for the current desktop host
    cmds:
      - task: '{{OS}}:run'

  dev:
    summary: Run Wails development mode
    cmds:
      - wails3 dev -config ./build/config.yml -port {{.VITE_PORT}}
