// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService exposes the stable application and settings bindings. Runtime and
 * session operations are added only when their controller owns the lifecycle.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ApplyAgentSettings(request: $models.ApplyAgentSettingsRequestDTO): $CancellablePromise<$models.AgentRuntimeStatusDTO> {
    return $Call.ByID(1025413539, request);
}

export function BeginWhatsAppPairing(request: $models.BeginWhatsAppPairingRequestDTO): $CancellablePromise<$models.WhatsAppSessionOperationDTO> {
    return $Call.ByID(2833984550, request);
}

export function CancelWhatsAppPairing(operationID: string): $CancellablePromise<$models.WhatsAppSessionStatusDTO> {
    return $Call.ByID(3187940753, operationID);
}

export function DeleteWhatsAppMessage(chatID: string, messageID: string): $CancellablePromise<void> {
    return $Call.ByID(4126946629, chatID, messageID);
}

export function GetAgentRuntimeStatus(): $CancellablePromise<$models.AgentRuntimeStatusDTO> {
    return $Call.ByID(1640000984);
}

export function GetAppInfo(): $CancellablePromise<$models.AppInfo> {
    return $Call.ByID(1606186488);
}

/**
 * GetLogs returns the newest safe application events captured in this run.
 */
export function GetLogs(): $CancellablePromise<$models.LogEntryDTO[] | null> {
    return $Call.ByID(1753640526);
}

/**
 * GetSettings returns the current public settings snapshot. Secret values are
 * replaced by configured flags inside the DTO conversion.
 */
export function GetSettings(): $CancellablePromise<$models.SettingsViewDTO> {
    return $Call.ByID(219153200);
}

/**
 * GetSettingsSchema returns the typed field catalog used by the form.
 */
export function GetSettingsSchema(): $CancellablePromise<$models.FieldDescriptorDTO[] | null> {
    return $Call.ByID(1479220523);
}

export function GetWhatsAppChatSettings(chatID: string): $CancellablePromise<$models.WhatsAppChatSettingsDTO> {
    return $Call.ByID(3685747852, chatID);
}

export function GetWhatsAppConversations(): $CancellablePromise<$models.WhatsAppConversationDTO[] | null> {
    return $Call.ByID(568159641);
}

export function GetWhatsAppGroupMembers(chatID: string): $CancellablePromise<$models.WhatsAppGroupMembersDTO> {
    return $Call.ByID(1637618105, chatID);
}

export function GetWhatsAppMessages(chatID: string): $CancellablePromise<$models.WhatsAppMessageDTO[] | null> {
    return $Call.ByID(2315394807, chatID);
}

export function GetWhatsAppSessionStatus(): $CancellablePromise<$models.WhatsAppSessionStatusDTO> {
    return $Call.ByID(1227179819);
}

export function KickWhatsAppGroupMember(chatID: string, memberID: string): $CancellablePromise<void> {
    return $Call.ByID(2898311284, chatID, memberID);
}

export function LogoutWhatsAppSession(): $CancellablePromise<$models.WhatsAppSessionOperationDTO> {
    return $Call.ByID(4192932161);
}

/**
 * Ping provides an explicit UI action for checking the Go-to-frontend event path.
 */
export function Ping(): $CancellablePromise<void> {
    return $Call.ByID(752415863);
}

export function ReconnectWhatsAppSession(): $CancellablePromise<$models.WhatsAppSessionOperationDTO> {
    return $Call.ByID(3156183818);
}

export function ResumeWhatsAppSession(): $CancellablePromise<$models.WhatsAppSessionOperationDTO> {
    return $Call.ByID(198429154);
}

/**
 * SaveSettings persists a validated draft with compare-and-swap revision
 * semantics. The response contains the new public revision and readiness.
 */
export function SaveSettings(request: $models.SaveSettingsRequestDTO): $CancellablePromise<$models.SaveSettingsResultDTO> {
    return $Call.ByID(527042219, request);
}

export function SaveWhatsAppChatSettings(request: $models.SaveWhatsAppChatSettingsRequestDTO): $CancellablePromise<$models.WhatsAppChatSettingsDTO> {
    return $Call.ByID(3459881951, request);
}

export function SendWhatsAppMessage(chatID: string, text: string, replyToMessageID: string): $CancellablePromise<$models.WhatsAppMessageDTO> {
    return $Call.ByID(1692344886, chatID, text, replyToMessageID);
}

export function StartAgent(): $CancellablePromise<$models.AgentRuntimeStatusDTO> {
    return $Call.ByID(508860618);
}

export function StopAgent(): $CancellablePromise<$models.AgentRuntimeStatusDTO> {
    return $Call.ByID(4252616312);
}

export function StopWhatsAppSession(): $CancellablePromise<$models.WhatsAppSessionStatusDTO> {
    return $Call.ByID(2473183791);
}

/**
 * ValidateSettings validates a complete public draft without persisting it.
 */
export function ValidateSettings(request: $models.SettingsPatchDTO): $CancellablePromise<$models.ValidationResultDTO> {
    return $Call.ByID(3868475520, request);
}
