// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../../config/models.js";

export interface AgentRuntimeStatusDTO {
    "state": string;
    "savedRevision": string;
    "activeRevision": string;
    "pendingChanges": boolean;
    "whatsAppState": string;
    "errorCode"?: string;
    "operationID"?: string;
}

/**
 * AppInfo is the small, stable information contract used by the first GUI binding.
 */
export interface AppInfo {
    "name": string;
    "version": string;
    "platform": string;
}

export interface ApplyAgentSettingsRequestDTO {
    "expectedRevision": string;
}

export interface BeginWhatsAppPairingRequestDTO {
    "method": string;
    "phone"?: string;
}

export interface FieldDescriptorDTO {
    "key": string;
    "group": string;
    "kind": string;
    "sensitive": boolean;
    "readOnly": boolean;
    "cliOnly": boolean;
    "default": string;
}

export interface LogEntryDTO {
    "time": string;
    "level": string;
    "message": string;
    "details": string;
}

/**
 * PingEvent is emitted on app:ping when Ping is called by the frontend.
 */
export interface PingEvent {
    "message": string;
    "sequence": number;
}

export interface ReadinessIssueDTO {
    "field": string;
    "code": string;
    "message": string;
}

export interface ResetWhatsAppChatSettingsRequestDTO {
    "expectedSettingsRevision": string;
    "category": string;
}

export interface ResetWhatsAppChatSettingsResultDTO {
    "changedChats": number;
}

export interface SaveSettingsRequestDTO {
    "expectedRevision": string;
    "patch": SettingsPatchDTO;
}

export interface SaveSettingsResultDTO {
    "view": SettingsViewDTO;
    "revision": string;
    "pendingChanges": boolean;
}

export interface SaveWhatsAppChatSettingsRequestDTO {
    "chatID": string;
    "expectedVersion": string;
    "moderationLevel": number;
    "promptOverrideMode": string;
    "promptOverrideText": string;
    "triggerMention": boolean;
    "triggerName": boolean;
    "triggerReply": boolean;
    "triggerNameRegex": boolean;
    "triggerNamePattern": string;
}

export interface ScheduleWhatsAppBroadcastRequestDTO {
    "groupIDs": string[] | null;
    "format": string;
    "payload": string;
    "batchSize": number;
    "batchDelaySeconds": number;
    "scheduledAt": string;
}

export interface SecretPatchDTO {
    "llmAPIKey": SecretUpdateDTO;
    "fallbackAPIKey": SecretUpdateDTO;
    "langSmithAPIKey": SecretUpdateDTO;
}

export interface SecretUpdateDTO {
    "action": string;
    "value"?: string;
}

export interface SendWhatsAppBroadcastRequestDTO {
    "groupIDs": string[] | null;
    "format": string;
    "payload": string;
    "batchSize": number;
    "batchDelaySeconds": number;
}

/**
 * SettingsPatchDTO accepts Draft as its canonical field. Settings and Values
 * remain harmless aliases for callers that use those names in their form
 * model; the first non-empty value wins in that order.
 */
export interface SettingsPatchDTO {
    "draft": SettingsValuesDTO;
    "settings": SettingsValuesDTO;
    "values": SettingsValuesDTO;
    "secrets": SecretPatchDTO;
}

/**
 * SettingsValuesDTO is the public settings form value. It deliberately does
 * not contain any secret value; configured is represented by the three
 * boolean status fields below.
 */
export interface SettingsValuesDTO {
    "assistantName": string;
    "basePrompt": string;
    "chatDefaults": config$0.ChatDefaults;
    "whatsAppEnabled": boolean;
    "agentEnabled": boolean;
    "ownerJID": string;
    "chatAllowlist": string[] | null;
    "llmEndpoint": string;
    "llmModel": string;
    "llmProviderID": string;
    "fallbackEndpoint": string;
    "llmTimeout": string;
    "llmConcurrency": number;
    "maxOutputTokens": number;
    "maxResponseBytes": number;
    "historyWindow": number;
    "maxContextBytes": number;
    "historyKeepLatest": number;
    "historyMaxAge": string;
    "inboundQueue": number;
    "inboundWorkers": number;
    "commandQueue": number;
    "commandWorkers": number;
    "aiQueue": number;
    "aiWorkers": number;
    "messageDebounce": string;
    "messageBurstCap": number;
    "agentMaxLive": number;
    "agentIdleTTL": string;
    "agentConstructionTimeout": string;
    "connectTimeout": string;
    "sendTimeout": string;
    "shutdownTimeout": string;
    "policyID": string;
    "policyRevision": string;
    "logLevel": string;
    "logFormat": string;
    "dataDir": string;
    "envFile": string;
    "httpAddress": string;
    "pairingOutput": string;
    "noColor": boolean;
    "forceColor": boolean;
    "startOnLaunch": boolean;

    /**
     * Identity is read-only bootstrap state. It is included so a complete
     * settings draft can be round-tripped without changing it to zero.
     */
    "tenantID": string;
    "accountID": string;
    "llmAPIKeyConfigured": boolean;
    "fallbackAPIKeyConfigured": boolean;
    "langSmithAPIKeyConfigured": boolean;
}

export interface SettingsViewDTO {
    "values": SettingsValuesDTO;
    "revision": string;
    "updatedAt": string;
    "readiness": ReadinessIssueDTO[] | null;
    "sessionReadiness": ReadinessIssueDTO[] | null;
    "agentReadiness": ReadinessIssueDTO[] | null;
}

export interface ValidationResultDTO {
    "valid": boolean;
    "readiness": ReadinessIssueDTO[] | null;
    "sessionReadiness": ReadinessIssueDTO[] | null;
    "agentReadiness": ReadinessIssueDTO[] | null;
}

export interface WhatsAppBroadcastGroupDTO {
    "id": string;
    "name": string;
}

export interface WhatsAppBroadcastGroupResultDTO {
    "id": string;
    "name": string;
    "sent": boolean;
    "errorCode": string;
}

export interface WhatsAppBroadcastScheduleDTO {
    "id": string;
    "scheduledAt": string;
    "batchSize": number;
    "batchDelaySeconds": number;
    "groupCount": number;
    "status": string;
    "results": WhatsAppBroadcastScheduleResultDTO[] | null;
}

export interface WhatsAppBroadcastScheduleResultDTO {
    "name": string;
    "sent": boolean;
    "errorCode": string;
}

export interface WhatsAppChatSettingsDTO {
    "version": string;
    "moderationLevel": number;
    "promptOverrideMode": string;
    "promptOverrideText": string;
    "triggerMention": boolean;
    "triggerName": boolean;
    "triggerReply": boolean;
    "triggerNameRegex": boolean;
    "triggerNamePattern": string;
}

export interface WhatsAppConversationDTO {
    "id": string;
    "kind": string;
    "name": string;
    "lastMessage": string;
    "lastMessageAt": string;
    "lastFromBot": boolean;
    "messageCount": number;
    "lastMessageMentions": WhatsAppMentionDTO[] | null;
}

export interface WhatsAppDailyUsageDTO {
    "date": string;
    "messages": number;
    "invocations": number;
}

export interface WhatsAppGroupMemberDTO {
    "id": string;
    "name": string;
    "isAdmin": boolean;
    "isSuperAdmin": boolean;
    "canKick": boolean;
}

export interface WhatsAppGroupMembersDTO {
    "botIsAdmin": boolean;
    "members": WhatsAppGroupMemberDTO[] | null;
}

export interface WhatsAppGroupUsageDTO {
    "name": string;
    "messages": number;
    "messagesInPeriod": number;
    "invocations": number;
    "invocationsInPeriod": number;
}

export interface WhatsAppMentionDTO {
    "token": string;
    "senderRef": string;
    "displayName": string;
    "bot": boolean;
}

export interface WhatsAppMessageDTO {
    "id": string;
    "role": string;
    "sender": string;
    "senderRef": string;
    "content": string;
    "isAdmin": boolean;
    "isSuperAdmin": boolean;
    "createdAt": string;
    "delivery": string;
    "deleted": boolean;
    "mentions": WhatsAppMentionDTO[] | null;
    "quote": WhatsAppQuoteDTO | null;
}

export interface WhatsAppPairingDTO {
    "method": string;
    "code"?: string;
    "qrCodeDataURL"?: string;
    "generation": number;
    "expiresAt": string;
}

export interface WhatsAppQuoteDTO {
    "messageID": string;
    "role": string;
    "sender": string;
    "content": string;
    "isAdmin": boolean;
    "isSuperAdmin": boolean;
    "mentions": WhatsAppMentionDTO[] | null;
}

export interface WhatsAppSessionEventDTO {
    "operationID": string;
    "status": WhatsAppSessionStatusDTO;
}

export interface WhatsAppSessionOperationDTO {
    "operationID": string;
    "status": WhatsAppSessionStatusDTO;
}

export interface WhatsAppSessionStatusDTO {
    "bindingState": string;
    "runtimeState": string;
    "sessionPresent": boolean;
    "agentActive": boolean;
    "whatsAppAccountID"?: string;
    "operationID"?: string;
    "pairing"?: WhatsAppPairingDTO | null;
    "errorCode"?: string;
}

export interface WhatsAppUsageDTO {
    "totalMessages": number;
    "totalInvocations": number;
    "totalChats": number;
    "messagesInPeriod": number;
    "invocationsInPeriod": number;
    "activeChatsInPeriod": number;
    "totalGroups": number;
    "activeGroupsInPeriod": number;
    "periodStart": string;
    "periodDays": number;
    "groups": WhatsAppGroupUsageDTO[] | null;
    "invocationGroups": WhatsAppGroupUsageDTO[] | null;
    "dailyActivity": WhatsAppDailyUsageDTO[] | null;
}
