// Code generated by commandgen; DO NOT EDIT.

package commands

import "github.com/Chomosuke9/WazzapAgent-Go/internal/command"

var Descriptors = []command.Descriptor{
	DumpCommand,
	GroupCommand,
	HelpCommand,
	InfoCommand,
	PermissionCommand,
	PromptCommand,
	ResetCommand,
}
