// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService exposes the stable application and settings bindings. Runtime and
 * session operations are added only when their controller owns the lifecycle.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddDiscordChatTask(request: $models.AddDiscordChatTaskRequestDTO): $CancellablePromise<$models.DiscordChatTaskDTO> {
    return $Call.ByID(2468465970, request);
}

export function ApplyAgentSettings(request: $models.ApplyAgentSettingsRequestDTO): $CancellablePromise<$models.AgentRuntimeStatusDTO> {
    return $Call.ByID(509027352, request);
}

export function BeginDiscordLink(request: $models.BeginDiscordLinkRequestDTO): $CancellablePromise<$models.DiscordSessionOperationDTO> {
    return $Call.ByID(2347959433, request);
}

export function CancelDiscordBroadcastSchedule(id: string): $CancellablePromise<void> {
    return $Call.ByID(2904896898, id);
}

export function CancelDiscordLink(operationID: string): $CancellablePromise<$models.DiscordSessionStatusDTO> {
    return $Call.ByID(2195800292, operationID);
}

export function DeleteDiscordChatTask(chatID: string, taskID: string, daily: boolean): $CancellablePromise<void> {
    return $Call.ByID(758351354, chatID, taskID, daily);
}

export function DeleteDiscordMessage(chatID: string, messageID: string): $CancellablePromise<void> {
    return $Call.ByID(1138351972, chatID, messageID);
}

export function GetAgentRuntimeStatus(): $CancellablePromise<$models.AgentRuntimeStatusDTO> {
    return $Call.ByID(2091639445);
}

export function GetAppInfo(): $CancellablePromise<$models.AppInfo> {
    return $Call.ByID(3455654739);
}

/**
 * GetLogDetails returns the full text of one warning or error: every logged
 * field and the whole underlying error chain.
 */
export function GetLogDetails(id: number): $CancellablePromise<string> {
    return $Call.ByID(1905880396, id);
}

/**
 * GetLogs returns the newest application events, including the warnings and
 * errors kept from earlier runs. HasFull marks entries whose full error text
 * GetLogDetails can return.
 */
export function GetLogs(): $CancellablePromise<$models.LogEntryDTO[] | null> {
    return $Call.ByID(34595455);
}

/**
 * GetSettings returns the current public settings snapshot. Secret values are
 * replaced by configured flags inside the DTO conversion.
 */
export function GetSettings(): $CancellablePromise<$models.SettingsViewDTO> {
    return $Call.ByID(1289645321);
}

/**
 * GetSettingsSchema returns the typed field catalog used by the form.
 */
export function GetSettingsSchema(): $CancellablePromise<$models.FieldDescriptorDTO[] | null> {
    return $Call.ByID(3845202794);
}

export function GetDiscordBroadcastGroups(): $CancellablePromise<$models.DiscordBroadcastGroupDTO[] | null> {
    return $Call.ByID(810744949);
}

export function GetDiscordBroadcastSchedules(): $CancellablePromise<$models.DiscordBroadcastScheduleDTO[] | null> {
    return $Call.ByID(350665621);
}

export function GetDiscordChatSettings(chatID: string): $CancellablePromise<$models.DiscordChatSettingsDTO> {
    return $Call.ByID(4054277929, chatID);
}

export function GetDiscordChatTasks(chatID: string): $CancellablePromise<$models.DiscordChatTaskDTO[] | null> {
    return $Call.ByID(481462102, chatID);
}

export function GetDiscordConversations(): $CancellablePromise<$models.DiscordConversationDTO[] | null> {
    return $Call.ByID(740320734);
}

export function GetDiscordGroupMembers(chatID: string): $CancellablePromise<$models.DiscordGroupMembersDTO> {
    return $Call.ByID(1218717640, chatID);
}

export function GetDiscordMessages(chatID: string): $CancellablePromise<$models.DiscordMessageDTO[] | null> {
    return $Call.ByID(3694365174, chatID);
}

export function GetDiscordSessionStatus(): $CancellablePromise<$models.DiscordSessionStatusDTO> {
    return $Call.ByID(883222112);
}

export function GetDiscordUsage(periodDays: number): $CancellablePromise<$models.DiscordUsageDTO> {
    return $Call.ByID(473878469, periodDays);
}

export function KickDiscordGroupMember(chatID: string, memberID: string): $CancellablePromise<void> {
    return $Call.ByID(3817692965, chatID, memberID);
}

export function UnlinkDiscordBot(): $CancellablePromise<$models.DiscordSessionOperationDTO> {
    return $Call.ByID(1117522952);
}

export function NormalizeDiscordBroadcastPayload(payload: string): $CancellablePromise<string> {
    return $Call.ByID(4213671378, payload);
}

export function ReconnectDiscordSession(): $CancellablePromise<$models.DiscordSessionOperationDTO> {
    return $Call.ByID(2930031041);
}

export function ResetDiscordChatSettings(request: $models.ResetDiscordChatSettingsRequestDTO): $CancellablePromise<$models.ResetDiscordChatSettingsResultDTO> {
    return $Call.ByID(3611806730, request);
}

export function ResumeDiscordSession(): $CancellablePromise<$models.DiscordSessionOperationDTO> {
    return $Call.ByID(3070900063);
}

/**
 * SaveSettings persists a validated draft with compare-and-swap revision
 * semantics. The response contains the new public revision and readiness.
 */
export function SaveSettings(request: $models.SaveSettingsRequestDTO): $CancellablePromise<$models.SaveSettingsResultDTO> {
    return $Call.ByID(3129592632, request);
}

export function SaveDiscordChatSettings(request: $models.SaveDiscordChatSettingsRequestDTO): $CancellablePromise<$models.DiscordChatSettingsDTO> {
    return $Call.ByID(4255998644, request);
}

export function ScheduleDiscordBroadcast(request: $models.ScheduleDiscordBroadcastRequestDTO): $CancellablePromise<$models.DiscordBroadcastScheduleDTO> {
    return $Call.ByID(3436800614, request);
}

export function SendDiscordBroadcast(request: $models.SendDiscordBroadcastRequestDTO): $CancellablePromise<$models.DiscordBroadcastGroupResultDTO[] | null> {
    return $Call.ByID(3320907247, request);
}

export function SendDiscordMessage(chatID: string, text: string, replyToMessageID: string): $CancellablePromise<$models.DiscordMessageDTO> {
    return $Call.ByID(2039765299, chatID, text, replyToMessageID);
}

export function StartAgent(): $CancellablePromise<$models.AgentRuntimeStatusDTO> {
    return $Call.ByID(3380803197);
}

export function StopAgent(): $CancellablePromise<$models.AgentRuntimeStatusDTO> {
    return $Call.ByID(3746750561);
}

export function StopDiscordSession(): $CancellablePromise<$models.DiscordSessionStatusDTO> {
    return $Call.ByID(1011256410);
}

/**
 * ValidateSettings validates a complete public draft without persisting it.
 */
export function ValidateSettings(request: $models.SettingsPatchDTO): $CancellablePromise<$models.ValidationResultDTO> {
    return $Call.ByID(2304830299, request);
}
