// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService exposes the stable application and settings bindings. Runtime and
 * session operations are added only when their controller owns the lifecycle.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddDiscordChatTask(request: $models.AddDiscordChatTaskRequestDTO): $CancellablePromise<$models.DiscordChatTaskDTO> {
    return $Call.ByID(3239797179, request);
}

export function ApplyAgentSettings(request: $models.ApplyAgentSettingsRequestDTO): $CancellablePromise<$models.AgentRuntimeStatusDTO> {
    return $Call.ByID(1747049417, request);
}

export function BeginDiscordLink(request: $models.BeginDiscordLinkRequestDTO): $CancellablePromise<$models.DiscordSessionOperationDTO> {
    return $Call.ByID(3436414222, request);
}

export function CancelDiscordBroadcastSchedule(id: string): $CancellablePromise<void> {
    return $Call.ByID(3459075401, id);
}

export function CancelDiscordLink(operationID: string): $CancellablePromise<$models.DiscordSessionStatusDTO> {
    return $Call.ByID(902051289, operationID);
}

export function DeleteDiscordChatTask(chatID: string, taskID: string, daily: boolean): $CancellablePromise<void> {
    return $Call.ByID(3834561913, chatID, taskID, daily);
}

export function DeleteDiscordMessage(chatID: string, messageID: string): $CancellablePromise<void> {
    return $Call.ByID(2817810553, chatID, messageID);
}

export function GetAgentRuntimeStatus(): $CancellablePromise<$models.AgentRuntimeStatusDTO> {
    return $Call.ByID(836636054);
}

export function GetAppInfo(): $CancellablePromise<$models.AppInfo> {
    return $Call.ByID(2963745550);
}

export function GetDiscordBroadcastGroups(): $CancellablePromise<$models.DiscordBroadcastGroupDTO[] | null> {
    return $Call.ByID(1447860280);
}

export function GetDiscordBroadcastSchedules(): $CancellablePromise<$models.DiscordBroadcastScheduleDTO[] | null> {
    return $Call.ByID(2592519714);
}

export function GetDiscordChatSettings(chatID: string): $CancellablePromise<$models.DiscordChatSettingsDTO> {
    return $Call.ByID(3209652538, chatID);
}

export function GetDiscordChatTasks(chatID: string): $CancellablePromise<$models.DiscordChatTaskDTO[] | null> {
    return $Call.ByID(3960120359, chatID);
}

export function GetDiscordConversations(): $CancellablePromise<$models.DiscordConversationDTO[] | null> {
    return $Call.ByID(4195453715);
}

export function GetDiscordGroupMembers(chatID: string): $CancellablePromise<$models.DiscordGroupMembersDTO> {
    return $Call.ByID(2269004067, chatID);
}

export function GetDiscordMessages(chatID: string): $CancellablePromise<$models.DiscordMessageDTO[] | null> {
    return $Call.ByID(108105977, chatID);
}

export function GetDiscordSessionStatus(): $CancellablePromise<$models.DiscordSessionStatusDTO> {
    return $Call.ByID(3300333837);
}

export function GetDiscordUsage(periodDays: number): $CancellablePromise<$models.DiscordUsageDTO> {
    return $Call.ByID(3113589324, periodDays);
}

/**
 * GetLogDetails returns the full text of one warning or error: every logged
 * field and the whole underlying error chain.
 */
export function GetLogDetails(id: number): $CancellablePromise<string> {
    return $Call.ByID(2958538139, id);
}

/**
 * GetLogs returns the newest application events, including the warnings and
 * errors kept from earlier runs. HasFull marks entries whose full error text
 * GetLogDetails can return.
 */
export function GetLogs(): $CancellablePromise<$models.LogEntryDTO[] | null> {
    return $Call.ByID(2108040056);
}

/**
 * GetSettings returns the current public settings snapshot. Secret values are
 * replaced by configured flags inside the DTO conversion.
 */
export function GetSettings(): $CancellablePromise<$models.SettingsViewDTO> {
    return $Call.ByID(3697906166);
}

/**
 * GetSettingsSchema returns the typed field catalog used by the form.
 */
export function GetSettingsSchema(): $CancellablePromise<$models.FieldDescriptorDTO[] | null> {
    return $Call.ByID(2992578001);
}

export function KickDiscordGroupMember(chatID: string, memberID: string): $CancellablePromise<void> {
    return $Call.ByID(2362528266, chatID, memberID);
}

export function NormalizeDiscordBroadcastPayload(payload: string): $CancellablePromise<string> {
    return $Call.ByID(4037423499, payload);
}

export function ReconnectDiscordSession(): $CancellablePromise<$models.DiscordSessionOperationDTO> {
    return $Call.ByID(1391683786);
}

export function ResetDiscordChatSettings(request: $models.ResetDiscordChatSettingsRequestDTO): $CancellablePromise<$models.ResetDiscordChatSettingsResultDTO> {
    return $Call.ByID(2533482903, request);
}

export function ResumeDiscordSession(): $CancellablePromise<$models.DiscordSessionOperationDTO> {
    return $Call.ByID(1239011318);
}

export function SaveDiscordChatSettings(request: $models.SaveDiscordChatSettingsRequestDTO): $CancellablePromise<$models.DiscordChatSettingsDTO> {
    return $Call.ByID(3142536655, request);
}

/**
 * SaveSettings persists a validated draft with compare-and-swap revision
 * semantics. The response contains the new public revision and readiness.
 */
export function SaveSettings(request: $models.SaveSettingsRequestDTO): $CancellablePromise<$models.SaveSettingsResultDTO> {
    return $Call.ByID(246240609, request);
}

export function ScheduleDiscordBroadcast(request: $models.ScheduleDiscordBroadcastRequestDTO): $CancellablePromise<$models.DiscordBroadcastScheduleDTO> {
    return $Call.ByID(2520459187, request);
}

export function SendDiscordBroadcast(request: $models.SendDiscordBroadcastRequestDTO): $CancellablePromise<$models.DiscordBroadcastGroupResultDTO[] | null> {
    return $Call.ByID(74942488, request);
}

export function SendDiscordMessage(chatID: string, text: string, replyToMessageID: string): $CancellablePromise<$models.DiscordMessageDTO> {
    return $Call.ByID(3442362800, chatID, text, replyToMessageID);
}

export function StartAgent(): $CancellablePromise<$models.AgentRuntimeStatusDTO> {
    return $Call.ByID(3471366936);
}

export function StopAgent(): $CancellablePromise<$models.AgentRuntimeStatusDTO> {
    return $Call.ByID(3935909906);
}

export function StopDiscordSession(): $CancellablePromise<$models.DiscordSessionStatusDTO> {
    return $Call.ByID(492027021);
}

export function UnlinkDiscordBot(): $CancellablePromise<$models.DiscordSessionOperationDTO> {
    return $Call.ByID(3151684387);
}

/**
 * ValidateSettings validates a complete public draft without persisting it.
 */
export function ValidateSettings(request: $models.SettingsPatchDTO): $CancellablePromise<$models.ValidationResultDTO> {
    return $Call.ByID(4038643370, request);
}
