// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";

/**
 * AddDiscordChatTaskRequestDTO adds a task that runs once at RunAt (RFC
 * 3339, within 24 hours) or, when Daily, every day at Time ("HH:MM" in the
 * bot's time zone).
 */
export interface AddDiscordChatTaskRequestDTO {
    "chatID": string;
    "prompt": string;
    "daily": boolean;
    "runAt": string;
    "time": string;
}

export interface AgentRuntimeStatusDTO {
    "state": string;
    "savedRevision": string;
    "activeRevision": string;
    "pendingChanges": boolean;
    "discordState": string;
    "errorCode"?: string;
    "operationID"?: string;
}

/**
 * AppInfo is the small, stable information contract used by the first GUI binding.
 */
export interface AppInfo {
    "name": string;
    "version": string;
    "platform": string;
}

export interface ApplyAgentSettingsRequestDTO {
    "expectedRevision": string;
}

export interface BeginDiscordLinkRequestDTO {
    "method": string;
    "phone"?: string;
}

export interface FieldDescriptorDTO {
    "key": string;
    "group": string;
    "kind": string;
    "sensitive": boolean;
    "readOnly": boolean;
    "cliOnly": boolean;
    "default": string;
}

export interface LogEntryDTO {
    "time": string;
    "level": string;
    "message": string;
    "details": string;
    "id": number;
    "hasFull": boolean;
}

export interface ReadinessIssueDTO {
    "field": string;
    "code": string;
    "message": string;
}

export interface ResetDiscordChatSettingsRequestDTO {
    "expectedSettingsRevision": string;
    "category": string;
}

export interface ResetDiscordChatSettingsResultDTO {
    "changedChats": number;
}

export interface SaveSettingsRequestDTO {
    "expectedRevision": string;
    "patch": SettingsPatchDTO;
}

export interface SaveSettingsResultDTO {
    "view": SettingsViewDTO;
    "revision": string;
    "pendingChanges": boolean;
}

export interface SaveDiscordChatSettingsRequestDTO {
    "chatID": string;
    "expectedVersion": string;
    "moderationLevel": number;
    "promptOverrideMode": string;
    "promptOverrideText": string;
    "triggerMention": boolean;
    "triggerName": boolean;
    "triggerReply": boolean;
    "triggerNameRegex": boolean;
    "triggerNamePattern": string;
    "triggerSmart": boolean;
    "triggerSmartRules": string;
}

export interface ScheduleDiscordBroadcastRequestDTO {
    "groupIDs": string[] | null;
    "format": string;
    "payload": string;
    "batchSize": number;
    "batchDelaySeconds": number;
    "scheduledAt": string;
}

export interface SecretPatchDTO {
    "llmAPIKey": SecretUpdateDTO;
    "fallbackAPIKey": SecretUpdateDTO;
    "langSmithAPIKey": SecretUpdateDTO;
    "typeSafeAPIKey": SecretUpdateDTO;
}

export interface SecretUpdateDTO {
    "action": string;
    "value"?: string;
}

export interface SendDiscordBroadcastRequestDTO {
    "groupIDs": string[] | null;
    "format": string;
    "payload": string;
    "batchSize": number;
    "batchDelaySeconds": number;
}

/**
 * SettingsPatchDTO accepts Draft as its canonical field. Settings and Values
 * remain harmless aliases for callers that use those names in their form
 * model; the first non-empty value wins in that order.
 */
export interface SettingsPatchDTO {
    "draft": SettingsValuesDTO;
    "settings": SettingsValuesDTO;
    "values": SettingsValuesDTO;
    "secrets": SecretPatchDTO;
}

/**
 * SettingsValuesDTO is the public settings form value. It deliberately does
 * not contain any secret value; configured is represented by the three
 * boolean status fields below.
 */
export interface SettingsValuesDTO {
    "assistantName": string;
    "basePrompt": string;
    "chatDefaults": config$0.ChatDefaults;
    "discordEnabled": boolean;
    "agentEnabled": boolean;
    "ownerJID": string;
    "chatAllowlist": string[] | null;
    "llmEndpoint": string;
    "llmModel": string;
    "llmProviderID": string;
    "fallbackEndpoint": string;
    "typeSafeEndpoint": string;
    "typeSafeModel": string;
    "llmTimeout": string;
    "llmConcurrency": number;
    "maxOutputTokens": number;
    "maxResponseBytes": number;
    "historyWindow": number;
    "maxContextBytes": number;
    "historyKeepLatest": number;
    "historyMaxAge": string;
    "inboundQueue": number;
    "inboundWorkers": number;
    "messageDebounce": string;
    "messageBurstCap": number;
    "connectTimeout": string;
    "sendTimeout": string;
    "shutdownTimeout": string;
    "policyID": string;
    "policyRevision": string;
    "logLevel": string;
    "logFormat": string;
    "dataDir": string;
    "envFile": string;
    "httpAddress": string;
    "pairingOutput": string;
    "noColor": boolean;
    "forceColor": boolean;
    "startOnLaunch": boolean;

    /**
     * Identity is read-only bootstrap state. It is included so a complete
     * settings draft can be round-tripped without changing it to zero.
     */
    "tenantID": string;
    "accountID": string;
    "llmAPIKeyConfigured": boolean;
    "fallbackAPIKeyConfigured": boolean;
    "langSmithAPIKeyConfigured": boolean;
    "typeSafeAPIKeyConfigured": boolean;
}

export interface SettingsViewDTO {
    "values": SettingsValuesDTO;
    "revision": string;
    "updatedAt": string;
    "readiness": ReadinessIssueDTO[] | null;
    "sessionReadiness": ReadinessIssueDTO[] | null;
    "agentReadiness": ReadinessIssueDTO[] | null;
}

export interface ValidationResultDTO {
    "valid": boolean;
    "readiness": ReadinessIssueDTO[] | null;
    "sessionReadiness": ReadinessIssueDTO[] | null;
    "agentReadiness": ReadinessIssueDTO[] | null;
}

export interface DiscordBroadcastGroupDTO {
    "id": string;
    "name": string;
}

export interface DiscordBroadcastGroupResultDTO {
    "id": string;
    "name": string;
    "sent": boolean;
    "errorCode": string;
}

export interface DiscordBroadcastScheduleDTO {
    "id": string;
    "scheduledAt": string;
    "batchSize": number;
    "batchDelaySeconds": number;
    "groupCount": number;
    "status": string;
    "results": DiscordBroadcastScheduleResultDTO[] | null;
}

export interface DiscordBroadcastScheduleResultDTO {
    "name": string;
    "sent": boolean;
    "errorCode": string;
}

export interface DiscordChatSettingsDTO {
    "version": string;
    "moderationLevel": number;
    "promptOverrideMode": string;
    "promptOverrideText": string;
    "triggerMention": boolean;
    "triggerName": boolean;
    "triggerReply": boolean;
    "triggerNameRegex": boolean;
    "triggerNamePattern": string;
    "triggerSmart": boolean;
    "triggerSmartRules": string;
}

/**
 * DiscordChatTaskDTO is a chat's scheduled (one-off) or daily task.
 */
export interface DiscordChatTaskDTO {
    "id": string;
    "prompt": string;

    /**
     * NextRun is RFC 3339 with the bot's UTC offset.
     */
    "nextRun": string;
    "daily": boolean;
}

export interface DiscordConversationDTO {
    "id": string;
    "kind": string;
    "name": string;
    "lastMessage": string;
    "lastMessageAt": string;
    "lastFromBot": boolean;
    "messageCount": number;
    "lastMessageMentions": DiscordMentionDTO[] | null;
}

export interface DiscordDailyUsageDTO {
    "date": string;
    "messages": number;
    "invocations": number;
}

export interface DiscordGroupMemberDTO {
    "id": string;
    "name": string;
    "isAdmin": boolean;
    "isSuperAdmin": boolean;
    "canKick": boolean;
}

export interface DiscordGroupMembersDTO {
    "botIsAdmin": boolean;
    "members": DiscordGroupMemberDTO[] | null;
}

export interface DiscordGroupUsageDTO {
    "name": string;
    "messages": number;
    "messagesInPeriod": number;
    "invocations": number;
    "invocationsInPeriod": number;
}

export interface DiscordMentionDTO {
    "token": string;
    "senderRef": string;
    "displayName": string;
    "bot": boolean;
}

export interface DiscordMessageDTO {
    "id": string;
    "role": string;
    "sender": string;
    "senderRef": string;
    "content": string;
    "isAdmin": boolean;
    "isSuperAdmin": boolean;
    "createdAt": string;
    "delivery": string;
    "deleted": boolean;
    "mentions": DiscordMentionDTO[] | null;
    "quote": DiscordQuoteDTO | null;
}

export interface DiscordPairingDTO {
    "method": string;
    "code"?: string;
    "qrCodeDataURL"?: string;
    "generation": number;
    "expiresAt": string;
}

export interface DiscordQuoteDTO {
    "messageID": string;
    "role": string;
    "sender": string;
    "content": string;
    "isAdmin": boolean;
    "isSuperAdmin": boolean;
    "mentions": DiscordMentionDTO[] | null;
}

export interface DiscordSessionOperationDTO {
    "operationID": string;
    "status": DiscordSessionStatusDTO;
}

export interface DiscordSessionStatusDTO {
    "bindingState": string;
    "runtimeState": string;
    "sessionPresent": boolean;
    "agentActive": boolean;
    "discordBotID"?: string;
    "operationID"?: string;
    "pairing"?: DiscordPairingDTO | null;
    "errorCode"?: string;
}

export interface DiscordUsageDTO {
    "totalMessages": number;
    "totalInvocations": number;
    "totalChats": number;
    "messagesInPeriod": number;
    "invocationsInPeriod": number;
    "activeChatsInPeriod": number;
    "totalGroups": number;
    "activeGroupsInPeriod": number;
    "periodStart": string;
    "periodDays": number;
    "groups": DiscordGroupUsageDTO[] | null;
    "invocationGroups": DiscordGroupUsageDTO[] | null;
    "dailyActivity": DiscordDailyUsageDTO[] | null;
}
