// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ChatDefaults {
    "moderationLevel": number;
    "promptMode": string;
    "promptText": string;
    "triggerMention": boolean;
    "triggerName": boolean;
    "triggerReply": boolean;
    "triggerNameRegex": boolean;
    "triggerNamePattern": string;
}
